version: '5'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  catalog.api:
    build:
      context: .
      dockerfile: Src/Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    build:
      context: .
      dockerfile: Src/Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    build:
      context: .
      dockerfile: Src/Services/Discount.Grpc/Dockerfile

  ordering.api:
    build:
      context: .
      dockerfile: Src/Services/Ordering/Ordering.API/Dockerfile
  media:
    image: media
    build:
      context: .
      dockerfile: Src/Services/Media/Media/Dockerfile

      
volumes:
  postgres_catalog:
  postgres_basket:


