# This is a generated file. Not intended for manual editing.
services:
  catalog.api:
    build:
      context: "C:\\Users\\Pedram\\source\\repos\\EShop_MicroService"
      dockerfile: "Src/Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\Pedram\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Pedram\\source\\repos\\EShop_MicroService\\Src\\Services\\Catalog\\\
      Catalog.API:/app:rw"
    - "C:\\Users\\Pedram\\source\\repos\\EShop_MicroService:/src:rw"
    working_dir: "/app"
