// <auto-generated />
using System;
using ElectronBoard.Infrastructure.SqlServer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronBoard.Infrastructure.Migrations
{
    [DbContext(typeof(ElectionDbContext))]
    [Migration("20241118180213_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectronBoard.Domain.Entities.ElectionCycle", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Year"));

                    b.Property<DateOnly?>("EndOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartOn")
                        .HasColumnType("date");

                    b.HasKey("Year");

                    b.ToTable("ElectionCycles");
                });

            modelBuilder.Entity("ElectronBoard.Domain.Entities.ElectionCycleVote", b =>
                {
                    b.Property<int>("ElectionCycle")
                        .HasColumnType("int");

                    b.Property<string>("FipsCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ElectionCycleYear")
                        .HasColumnType("int");

                    b.Property<long>("Votes")
                        .HasColumnType("bigint");

                    b.HasKey("ElectionCycle", "FipsCode");

                    b.HasIndex("ElectionCycleYear");

                    b.ToTable("ElectionCycleVotes");
                });

            modelBuilder.Entity("ElectronBoard.Domain.Entities.State", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ElectralVotes")
                        .HasColumnType("int");

                    b.Property<string>("FipsCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("States");
                });

            modelBuilder.Entity("ElectronBoard.Domain.Entities.ElectionCycleVote", b =>
                {
                    b.HasOne("ElectronBoard.Domain.Entities.ElectionCycle", null)
                        .WithMany("Candidates")
                        .HasForeignKey("ElectionCycleYear");
                });

            modelBuilder.Entity("ElectronBoard.Domain.Entities.ElectionCycle", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
